version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sirh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/sirh
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
volumes:
  db-data:
